---
title: "Growth Curves"
output: html_notebook
---

```{r}
library(growthcurve)
library(tidyverse)
```

```{r}
Sc30_OD <- read_delim("~/Dropbox/! Diezmann Lab/R/Networks/GrowthCurves/Sc30_OD.txt",
"\t", escape_double = FALSE, trim_ws = TRUE)
colnames(Sc30_OD)[1] <- 'Time'
Sc30_fit <-fit_growth(Sc30_OD, Time, YPD, type='logistic')
Sc30_fit$parameters
```

```{r}
Ca_301216 <- read_delim("~/Dropbox/! Diezmann Lab/R/Buffering/Ca_301216.txt",
"\t", escape_double = FALSE, trim_ws = TRUE)
Ca_301216<-gather(Ca_301216, Time, OD, -Well)
Ca_301216$Time = as.numeric(Ca_301216$Time)
Ca_301216 <- mutate(Ca_301216, Row = substr(Well, 1, 1), Column = as.numeric(substr(Well, 2, nchar(Well))))
Ca_301216_fit <- group_by(Ca_301216, Well, Row, Column) %>% 
  nest() %>% 
  mutate(fit=map(data, ~ fit_growth(., Time, OD, type='logistic'))) %>% 
  mutate(Vmax=map(map(map(map(fit, 3), 'parameters'), 'A'), 1),
         VmaxSE=map(map(map(map(fit, 3), 'parameters'), 'A'), 2),
         max_rate=map(map(map(map(fit, 3), 'parameters'), 'mu'), 1),
         max_rateSE=map(map(map(map(fit, 3), 'parameters'), 'mu'), 2)) %>%
         unnest(Vmax, VmaxSE, max_rate, max_rateSE)
select(Ca_301216_fit, Well, Vmax, VmaxSE, max_rate, max_rateSE) %>%
  write_tsv("~/Dropbox/! Diezmann Lab/R/Buffering/Ca_301216_results.txt")
```
```{r}


ggplot(Ca_301216, aes(x=Time, y=OD, group=Well)) +
      geom_line() +
      #geom_label(aes(label=Vmax), data=Ca_301216_fit) +
      geom_text(data=Ca_301216_fit, aes(label = signif(Vmax, 4)), x=22000, y=1.8, size=2) +
      facet_grid(Row ~ Column) +
      theme(axis.text=element_blank()) +
      theme(axis.ticks=element_blank()) +
      theme(legend.position="bottom") +
      theme(legend.direction= "horizontal")
ggsave("~/Dropbox/! Diezmann Lab/R/Buffering/Ca_301216_grid.png")
```

